### ISSUE TITLE
Arduino/Genuino Uno.   

### ISSUE THREAD

**Issue by engabuhadi** [arduino-libraries/AudioFrequencyMeter#12]
Arduino: 1.8.8 (Windows 10), Board: "Arduino/Genuino Uno"

WARNING: library Audio claims to run on (sam) architecture(s) and may be incompatible with your current board which runs on (avr) architecture(s).
In file included from C:\Users\engab\Documents\Arduino\sketch_jan24a\sketch_jan24a.ino:11:0:

C:\Program Files (x86)\Arduino\libraries\Bridge\src/YunClient.h:24:2: warning: #warning "The use of YunClient is deprecated. Use BridgeClient instead!" [-Wcpp]

 #warning "The use of YunClient is deprecated. Use BridgeClient instead!"

  ^

In file included from C:\Users\engab\Documents\Arduino\sketch_jan24a\sketch_jan24a.ino:12:0:

C:\Program Files (x86)\Arduino\libraries\Bridge\src/YunServer.h:24:2: warning: #warning "The use of YunServer is deprecated. Use BridgeServer instead!" [-Wcpp]

 #warning "The use of YunServer is deprecated. Use BridgeServer instead!"

  ^

In file included from C:\Users\engab\Documents\Arduino\libraries\Audio\src/Audio.h:16:0,

                 from C:\Users\engab\Documents\Arduino\sketch_jan24a\sketch_jan24a.ino:14:

C:\Users\engab\Documents\Arduino\libraries\Audio\src/DAC.h:21:16: error: expected ')' before '*' token

  DACClass(Dacc *_dac, uint32_t _dacId, IRQn_Type _isrId) :

                ^

C:\Users\engab\Documents\Arduino\libraries\Audio\src/DAC.h:35:2: error: 'Dacc' does not name a type

  Dacc *dac;

  ^

C:\Users\engab\Documents\Arduino\libraries\Audio\src/DAC.h:37:2: error: 'IRQn_Type' does not name a type

  IRQn_Type isrId;

  ^

C:\Users\engab\Documents\Arduino\libraries\Audio\src/DAC.h: In member function 'void DACClass::enableInterrupts()':

C:\Users\engab\Documents\Arduino\libraries\Audio\src/DAC.h:31:44: error: 'isrId' was not declared in this scope

  void enableInterrupts()  { NVIC_EnableIRQ(isrId); };

                                            ^

C:\Users\engab\Documents\Arduino\libraries\Audio\src/DAC.h:31:49: error: 'NVIC_EnableIRQ' was not declared in this scope

  void enableInterrupts()  { NVIC_EnableIRQ(isrId); };

                                                 ^

C:\Users\engab\Documents\Arduino\libraries\Audio\src/DAC.h: In member function 'void DACClass::disableInterrupts()':

C:\Users\engab\Documents\Arduino\libraries\Audio\src/DAC.h:32:45: error: 'isrId' was not declared in this scope

  void disableInterrupts() { NVIC_DisableIRQ(isrId); };

                                             ^

C:\Users\engab\Documents\Arduino\libraries\Audio\src/DAC.h:32:50: error: 'NVIC_DisableIRQ' was not declared in this scope

  void disableInterrupts() { NVIC_DisableIRQ(isrId); };

                                                  ^

exit status 1
Error compiling for board Arduino/Genuino Uno.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by facchinm** [comment]
Hi @engabuhadi ,
unfortunately this library only supports SAMD boards (see the Readme).
