### ISSUE TITLE
the example does not work   Arduino ide 1.8.13

### ISSUE THREAD

**Issue by Bflorin-sk** [arduino-libraries/AudioFrequencyMeter#17]
Arduino: 1.8.13 (Windows Store 1.8.42.0) (Windows 10), Board: "Arduino Uno"

The sketch name had to be modified.
Sketch names must start with a letter or number, followed by letters,
numbers, dashes, dots and underscores. Maximum length is 63 characters.

WARNING: library AudioFrequencyMeter claims to run on samd architecture(s) and may be incompatible with your current board which runs on avr architecture(s).

C:\Users\Dell\Documents\Arduino\libraries\AudioFrequencyMeter\src\AudioFrequencyMeter.cpp: In member function 'void AudioFrequencyMeter::ADCconfigure()':

C:\Users\Dell\Documents\Arduino\libraries\AudioFrequencyMeter\src\AudioFrequencyMeter.cpp:163:6: error: base operand of '->' is not a pointer

   ADC->CTRLB.bit.RESSEL = ADC_CTRLB_RESSEL_8BIT_Val;

      ^~

C:\Users\Dell\Documents\Arduino\libraries\AudioFrequencyMeter\src\AudioFrequencyMeter.cpp:163:27: error: 'ADC_CTRLB_RESSEL_8BIT_Val' was not declared in this scope

   ADC->CTRLB.bit.RESSEL = ADC_CTRLB_RESSEL_8BIT_Val;

                           ^~~~~~~~~~~~~~~~~~~~~~~~~

C:\Users\Dell\Documents\Arduino\libraries\AudioFrequencyMeter\src\AudioFrequencyMeter.cpp:167:6: error: base operand of '->' is not a pointer

   ADC->CTRLB.bit.PRESCALER = ADC_CTRLB_PRESCALER_DIV8_Val;     // Divide Clock by 8 -> ~100kHz

      ^~

C:\Users\Dell\Documents\Arduino\libraries\AudioFrequencyMeter\src\AudioFrequencyMeter.cpp:167:30: error: 'ADC_CTRLB_PRESCALER_DIV8_Val' was not declared in this scope

   ADC->CTRLB.bit.PRESCALER = ADC_CTRLB_PRESCALER_DIV8_Val;     // Divide Clock by 8 -> ~100kHz

                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

C:\Users\Dell\Documents\Arduino\libraries\AudioFrequencyMeter\src\AudioFrequencyMeter.cpp:175:6: error: base operand of '->' is not a pointer

   ADC->SAMPCTRL.reg = 0x1F;                                    // Set max Sampling Time Length

      ^~

C:\Users\Dell\Documents\Arduino\libraries\AudioFrequencyMeter\src\AudioFrequencyMeter.cpp: In function 'bool ADCisSyncing()':

C:\Users\Dell\Documents\Arduino\libraries\AudioFrequencyMeter\src\AudioFrequencyMeter.cpp:184:14: error: base operand of '->' is not a pointer

   return (ADC->STATUS.bit.SYNCBUSY);

              ^~

C:\Users\Dell\Documents\Arduino\libraries\AudioFrequencyMeter\src\AudioFrequencyMeter.cpp: In member function 'void AudioFrequencyMeter::ADCdisable()':

C:\Users\Dell\Documents\Arduino\libraries\AudioFrequencyMeter\src\AudioFrequencyMeter.cpp:189:6: error: base operand of '->' is not a pointer

   ADC->CTRLA.bit.ENABLE = 0x00;                               // Disable ADC

      ^~

C:\Users\Dell\Documents\Arduino\libraries\AudioFrequencyMeter\src\AudioFrequencyMeter.cpp: In member function 'void AudioFrequencyMeter::ADCenable()':

C:\Users\Dell\Documents\Arduino\libraries\AudioFrequencyMeter\src\AudioFrequencyMeter.cpp:196:6: error: base operand of '->' is not a pointer

   ADC->CTRLA.bit.ENABLE = 0x01;                               // Enable ADC

      ^~

C:\Users\Dell\Documents\Arduino\libraries\AudioFrequencyMeter\src\AudioFrequencyMeter.cpp: In member function 'void AudioFrequencyMeter::ADCsetMux()':

C:\Users\Dell\Documents\Arduino\libraries\AudioFrequencyMeter\src\AudioFrequencyMeter.cpp:208:28: error: 'g_APinDescription' was not declared in this scope

   pinPeripheral(samplePin, g_APinDescription[samplePin].ulPinType);

                            ^~~~~~~~~~~~~~~~~

C:\Users\Dell\Documents\Arduino\libraries\AudioFrequencyMeter\src\AudioFrequencyMeter.cpp:208:3: error: 'pinPeripheral' was not declared in this scope

   pinPeripheral(samplePin, g_APinDescription[samplePin].ulPinType);

   ^~~~~~~~~~~~~

C:\Users\Dell\Documents\Arduino\libraries\AudioFrequencyMeter\src\AudioFrequencyMeter.cpp:212:6: error: base operand of '->' is not a pointer

   ADC->INPUTCTRL.bit.MUXPOS = g_APinDescription[samplePin].ulADCChannelNumber; // Selection for the positive ADC input

      ^~

C:\Users\Dell\Documents\Arduino\libraries\AudioFrequencyMeter\src\AudioFrequencyMeter.cpp: In member function 'void AudioFrequencyMeter::tcConfigure()':

C:\Users\Dell\Documents\Arduino\libraries\AudioFrequencyMeter\src\AudioFrequencyMeter.cpp:218:3: error: 'GCLK' was not declared in this scope

   GCLK->CLKCTRL.reg = (uint16_t) (GCLK_CLKCTRL_CLKEN | GCLK_CLKCTRL_GEN_GCLK0 | GCLK_CLKCTRL_ID(GCM_TC4_TC5)) ;

   ^~~~

C:\Users\Dell\Documents\Arduino\libraries\AudioFrequencyMeter\src\AudioFrequencyMeter.cpp:218:3: note: suggested alternative: 'SCL'

   GCLK->CLKCTRL.reg = (uint16_t) (GCLK_CLKCTRL_CLKEN | GCLK_CLKCTRL_GEN_GCLK0 | GCLK_CLKCTRL_ID(GCM_TC4_TC5)) ;

   ^~~~

   SCL

C:\Users\Dell\Documents\Arduino\libraries\AudioFrequencyMeter\src\AudioFrequencyMeter.cpp:218:35: error: 'GCLK_CLKCTRL_CLKEN' was not declared in this scope

   GCLK->CLKCTRL.reg = (uint16_t) (GCLK_CLKCTRL_CLKEN | GCLK_CLKCTRL_GEN_GCLK0 | GCLK_CLKCTRL_ID(GCM_TC4_TC5)) ;

                                   ^~~~~~~~~~~~~~~~~~

C:\Users\Dell\Documents\Arduino\libraries\AudioFrequencyMeter\src\AudioFrequencyMeter.cpp:218:56: error: 'GCLK_CLKCTRL_GEN_GCLK0' was not declared in this scope

   GCLK->CLKCTRL.reg = (uint16_t) (GCLK_CLKCTRL_CLKEN | GCLK_CLKCTRL_GEN_GCLK0 | GCLK_CLKCTRL_ID(GCM_TC4_TC5)) ;

                                                        ^~~~~~~~~~~~~~~~~~~~~~

C:\Users\Dell\Documents\Arduino\libraries\AudioFrequencyMeter\src\AudioFrequencyMeter.cpp:218:97: error: 'GCM_TC4_TC5' was not declared in this scope

   GCLK->CLKCTRL.reg = (uint16_t) (GCLK_CLKCTRL_CLKEN | GCLK_CLKCTRL_GEN_GCLK0 | GCLK_CLKCTRL_ID(GCM_TC4_TC5)) ;

                                                                                                 ^~~~~~~~~~~

C:\Users\Dell\Documents\Arduino\libraries\AudioFrequencyMeter\src\AudioFrequencyMeter.cpp:218:81: error: 'GCLK_CLKCTRL_ID' was not declared in this scope

   GCLK->CLKCTRL.reg = (uint16_t) (GCLK_CLKCTRL_CLKEN | GCLK_CLKCTRL_GEN_GCLK0 | GCLK_CLKCTRL_ID(GCM_TC4_TC5)) ;

                                                                                 ^~~~~~~~~~~~~~~

C:\Users\Dell\Documents\Arduino\libraries\AudioFrequencyMeter\src\AudioFrequencyMeter.cpp:224:3: error: 'TC5' was not declared in this scope

   TC5->COUNT16.CTRLA.reg |= TC_CTRLA_MODE_COUNT16;

   ^~~

C:\Users\Dell\Documents\Arduino\libraries\AudioFrequencyMeter\src\AudioFrequencyMeter.cpp:224:3: note: suggested alternative: 'PC5'

   TC5->COUNT16.CTRLA.reg |= TC_CTRLA_MODE_COUNT16;

   ^~~

   PC5

C:\Users\Dell\Documents\Arduino\libraries\AudioFrequencyMeter\src\AudioFrequencyMeter.cpp:224:29: error: 'TC_CTRLA_MODE_COUNT16' was not declared in this scope

   TC5->COUNT16.CTRLA.reg |= TC_CTRLA_MODE_COUNT16;

                             ^~~~~~~~~~~~~~~~~~~~~

C:\Users\Dell\Documents\Arduino\libraries\AudioFrequencyMeter\src\AudioFrequencyMeter.cpp:227:29: error: 'TC_CTRLA_WAVEGEN_MFRQ' was not declared in this scope

   TC5->COUNT16.CTRLA.reg |= TC_CTRLA_WAVEGEN_MFRQ;

                             ^~~~~~~~~~~~~~~~~~~~~

C:\Users\Dell\Documents\Arduino\libraries\AudioFrequencyMeter\src\AudioFrequencyMeter.cpp:229:29: error: 'TC_CTRLA_PRESCALER_DIV1' was not declared in this scope

   TC5->COUNT16.CTRLA.reg |= TC_CTRLA_PRESCALER_DIV1 | TC_CTRLA_ENABLE;

                             ^~~~~~~~~~~~~~~~~~~~~~~

C:\Users\Dell\Documents\Arduino\libraries\AudioFrequencyMeter\src\AudioFrequencyMeter.cpp:229:55: error: 'TC_CTRLA_ENABLE' was not declared in this scope

   TC5->COUNT16.CTRLA.reg |= TC_CTRLA_PRESCALER_DIV1 | TC_CTRLA_ENABLE;

                                                       ^~~~~~~~~~~~~~~

C:\Users\Dell\Documents\Arduino\libraries\AudioFrequencyMeter\src\AudioFrequencyMeter.cpp:231:40: error: 'SystemCoreClock' was not declared in this scope

   TC5->COUNT16.CC[0].reg = (uint16_t) (SystemCoreClock / sampleRate - 1);

                                        ^~~~~~~~~~~~~~~

C:\Users\Dell\Documents\Arduino\libraries\AudioFrequencyMeter\src\AudioFrequencyMeter.cpp:238:19: error: 'TC5_IRQn' was not declared in this scope

   NVIC_DisableIRQ(TC5_IRQn);

                   ^~~~~~~~

C:\Users\Dell\Documents\Arduino\libraries\AudioFrequencyMeter\src\AudioFrequencyMeter.cpp:238:3: error: 'NVIC_DisableIRQ' was not declared in this scope

   NVIC_DisableIRQ(TC5_IRQn);

   ^~~~~~~~~~~~~~~

C:\Users\Dell\Documents\Arduino\libraries\AudioFrequencyMeter\src\AudioFrequencyMeter.cpp:239:3: error: 'NVIC_ClearPendingIRQ' was not declared in this scope

   NVIC_ClearPendingIRQ(TC5_IRQn);

   ^~~~~~~~~~~~~~~~~~~~

C:\Users\Dell\Documents\Arduino\libraries\AudioFrequencyMeter\src\AudioFrequencyMeter.cpp:240:3: error: 'NVIC_SetPriority' was not declared in this scope

   NVIC_SetPriority(TC5_IRQn, 0x00);

   ^~~~~~~~~~~~~~~~

C:\Users\Dell\Documents\Arduino\libraries\AudioFrequencyMeter\src\AudioFrequencyMeter.cpp:241:3: error: 'NVIC_EnableIRQ' was not declared in this scope

   NVIC_EnableIRQ(TC5_IRQn);

   ^~~~~~~~~~~~~~

C:\Users\Dell\Documents\Arduino\libraries\AudioFrequencyMeter\src\AudioFrequencyMeter.cpp: In member function 'bool AudioFrequencyMeter::tcIsSyncing()':

C:\Users\Dell\Documents\Arduino\libraries\AudioFrequencyMeter\src\AudioFrequencyMeter.cpp:251:10: error: 'TC5' was not declared in this scope

   return TC5->COUNT16.STATUS.reg & TC_STATUS_SYNCBUSY;

          ^~~

C:\Users\Dell\Documents\Arduino\libraries\AudioFrequencyMeter\src\AudioFrequencyMeter.cpp:251:10: note: suggested alternative: 'PC5'

   return TC5->COUNT16.STATUS.reg & TC_STATUS_SYNCBUSY;

          ^~~

          PC5

C:\Users\Dell\Documents\Arduino\libraries\AudioFrequencyMeter\src\AudioFrequencyMeter.cpp:251:36: error: 'TC_STATUS_SYNCBUSY' was not declared in this scope

   return TC5->COUNT16.STATUS.reg & TC_STATUS_SYNCBUSY;

                                    ^~~~~~~~~~~~~~~~~~

C:\Users\Dell\Documents\Arduino\libraries\AudioFrequencyMeter\src\AudioFrequencyMeter.cpp: In member function 'void AudioFrequencyMeter::tcEnable()':

C:\Users\Dell\Documents\Arduino\libraries\AudioFrequencyMeter\src\AudioFrequencyMeter.cpp:256:3: error: 'TC5' was not declared in this scope

   TC5->COUNT16.CTRLA.reg |= TC_CTRLA_ENABLE;

   ^~~

C:\Users\Dell\Documents\Arduino\libraries\AudioFrequencyMeter\src\AudioFrequencyMeter.cpp:256:3: note: suggested alternative: 'PC5'

   TC5->COUNT16.CTRLA.reg |= TC_CTRLA_ENABLE;

   ^~~

   PC5

C:\Users\Dell\Documents\Arduino\libraries\AudioFrequencyMeter\src\AudioFrequencyMeter.cpp:256:29: error: 'TC_CTRLA_ENABLE' was not declared in this scope

   TC5->COUNT16.CTRLA.reg |= TC_CTRLA_ENABLE;

                             ^~~~~~~~~~~~~~~

C:\Users\Dell\Documents\Arduino\libraries\AudioFrequencyMeter\src\AudioFrequencyMeter.cpp: In member function 'void AudioFrequencyMeter::tcReset()':

C:\Users\Dell\Documents\Arduino\libraries\AudioFrequencyMeter\src\AudioFrequencyMeter.cpp:263:3: error: 'TC5' was not declared in this scope

   TC5->COUNT16.CTRLA.reg = TC_CTRLA_SWRST;

   ^~~

C:\Users\Dell\Documents\Arduino\libraries\AudioFrequencyMeter\src\AudioFrequencyMeter.cpp:263:3: note: suggested alternative: 'PC5'

   TC5->COUNT16.CTRLA.reg = TC_CTRLA_SWRST;

   ^~~

   PC5

C:\Users\Dell\Documents\Arduino\libraries\AudioFrequencyMeter\src\AudioFrequencyMeter.cpp:263:28: error: 'TC_CTRLA_SWRST' was not declared in this scope

   TC5->COUNT16.CTRLA.reg = TC_CTRLA_SWRST;

                            ^~~~~~~~~~~~~~

C:\Users\Dell\Documents\Arduino\libraries\AudioFrequencyMeter\src\AudioFrequencyMeter.cpp: In member function 'void AudioFrequencyMeter::tcDisable()':

C:\Users\Dell\Documents\Arduino\libraries\AudioFrequencyMeter\src\AudioFrequencyMeter.cpp:273:3: error: 'TC5' was not declared in this scope

   TC5->COUNT16.CTRLA.reg &= ~TC_CTRLA_ENABLE;

   ^~~

C:\Users\Dell\Documents\Arduino\libraries\AudioFrequencyMeter\src\AudioFrequencyMeter.cpp:273:3: note: suggested alternative: 'PC5'

   TC5->COUNT16.CTRLA.reg &= ~TC_CTRLA_ENABLE;

   ^~~

   PC5

C:\Users\Dell\Documents\Arduino\libraries\AudioFrequencyMeter\src\AudioFrequencyMeter.cpp:273:30: error: 'TC_CTRLA_ENABLE' was not declared in this scope

   TC5->COUNT16.CTRLA.reg &= ~TC_CTRLA_ENABLE;

                              ^~~~~~~~~~~~~~~

C:\Users\Dell\Documents\Arduino\libraries\AudioFrequencyMeter\src\AudioFrequencyMeter.cpp: In function 'uint8_t ADCread()':

C:\Users\Dell\Documents\Arduino\libraries\AudioFrequencyMeter\src\AudioFrequencyMeter.cpp:285:6: error: base operand of '->' is not a pointer

   ADC->SWTRIG.bit.START = 1;

      ^~

C:\Users\Dell\Documents\Arduino\libraries\AudioFrequencyMeter\src\AudioFrequencyMeter.cpp:287:14: error: base operand of '->' is not a pointer

   while ( ADC->INTFLAG.bit.RESRDY == 0 );        // Waiting for conversion to complete

              ^~

C:\Users\Dell\Documents\Arduino\libraries\AudioFrequencyMeter\src\AudioFrequencyMeter.cpp:288:20: error: base operand of '->' is not a pointer

   returnValue = ADC->RESULT.reg;                 // Store the value

                    ^~

C:\Users\Dell\Documents\Arduino\libraries\AudioFrequencyMeter\src\AudioFrequencyMeter.cpp:293:6: error: base operand of '->' is not a pointer

   ADC->SWTRIG.bit.START = 0;

      ^~

C:\Users\Dell\Documents\Arduino\libraries\AudioFrequencyMeter\src\AudioFrequencyMeter.cpp: In function 'void TC5_Handler()':

C:\Users\Dell\Documents\Arduino\libraries\AudioFrequencyMeter\src\AudioFrequencyMeter.cpp:376:3: error: 'TC5' was not declared in this scope

   TC5->COUNT16.INTFLAG.bit.MC0 = 1;     // Clear interrupt

   ^~~

C:\Users\Dell\Documents\Arduino\libraries\AudioFrequencyMeter\src\AudioFrequencyMeter.cpp:376:3: note: suggested alternative: 'PC5'

   TC5->COUNT16.INTFLAG.bit.MC0 = 1;     // Clear interrupt

   ^~~

   PC5

exit status 1

Error compiling for board Arduino Uno.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by per1234** [comment]
>WARNING: library AudioFrequencyMeter claims to run on samd architecture(s) and may be incompatible with your current board which runs on avr architecture(s).

As the warning says, this library is not compatible with the avr architecture of your Arduino Uno board. You can only use it with the SAMD boards like the [Nano 33 IoT](https://store.arduino.cc/usa/nano-33-iot), [MKR Zero](https://store.arduino.cc/usa/arduino-mkrzero), [MKR WiFi 1010](https://store.arduino.cc/usa/mkr-wifi-1010), [Zero](https://store.arduino.cc/usa/arduino-zero), etc.

If you have a SAMD board, make sure you select it from the Arduino IDE's **Tools > Board** menu. If you don't have a SAMD board, you can't use this library.
