### ISSUE TITLE
Begin Function stuck

### ISSUE THREAD

**Issue by bjsmyth** [arduino-libraries/AudioFrequencyMeter#5]
Trying to run the frequency meter with begin(A0, 960000) with frequency meter version 1.0.2 and board support version 1.6.6. The sketch does not run past the begin function but will start running the rest if the integer is lowered down, say to 900000.

**Comment by rishi-electronut** [comment]
I am trying to run the example code on a Neutrino board ( SAMD21G18A, ARM M0+).
The input is a sine wave generated by AudaCity software at 440Hz.
The serial monitor only displays -1.00 Hz.
Any idea what's going on here?
