### ISSUE TITLE
Ambiguous output on Serial monitor

### ISSUE THREAD

**Issue by rishi-electronut** [arduino-libraries/AudioFrequencyMeter#6]
I am trying to run the example code on a Neutrino board ( SAMD21G18A, ARM M0+).
The input is a sine wave generated by AudaCity software at 440Hz.
The serial monitor only displays -1.00 Hz.
Any idea what's going on here?

**Comment by lokeshVK** [comment]
Hey will it work on Arduino M0?

**Comment by agdl** [comment]
@lokeshVK yes it will

**Comment by lokeshVK** [comment]
What about Arduino Uno then? Will I be able to use the library with Uno?

**Comment by agdl** [comment]
@lokeshVK no, see https://github.com/arduino-libraries/AudioFrequencyMeter/issues/7
