### ISSUE TITLE
Arduino Uno Compatibility

### ISSUE THREAD

**Issue by jennab16** [arduino-libraries/AudioFrequencyMeter#7]
Is there any way to make this compatible for the Arduino Uno? I'm pretty new to Arduino programming so maybe this is a dumb question, but if you could enlighten me anyway that would be great! Thank you

**Comment by dmarkey** [comment]
Me too!

**Comment by agdl** [comment]
This library works on SAMD21 based boards ONLY like MKR1000, MKRZero and Zero

To have something similar on the UNO try this http://www.instructables.com/id/Arduino-Frequency-Detection/

**Comment by lokeshVK** [comment]
Okay cool thanks buddy.
